### ISSUE TITLE
Issue in Return?

### ISSUE THREAD

**Issue by to11mtm** [AliKhalili/heartbeat#2]
Good article BTW.

While reviewing the code however I noticed the following in the pool logic:

https://github.com/AliKhalili/heartbeat/blob/bf8f44a03d4c38ac3e8f65d43fca1d0ba9f63677/src/SocketAsyncEventArgsPool.cs#L28-L30

Namely, 
`if (_enabled || _disposed || Interlocked.Increment(ref _count) > MaxQueueSize)`

Should this be 
`if (!_enabled || _disposed || Interlocked.Increment(ref _count) > MaxQueueSize)`?

**Comment by AliKhalili** [comment]
nice one, that's correct, will fix it and rerun benchmarks again
